In [2]:
#Importing Pandas
import pandas as pd

In [3]:
#Creating a Series from a List
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [ ]:
#Creating a Series from a Dictionary
data={
    'a':1,
    'b':2,
    'c':3
}
series=pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64

In [5]:
#Creating a Series with a Custom Index
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [7]:
#Creating a DataFrame from a Dictionary
data={
    'Name':['Aryan','Krish','John'],
    'Age':[20,30,45],
    'City':['Kolkata','Bangalore','Florida'] 
}
df=pd.DataFrame(data)
df

    Name  Age       City
0  Aryan   20    Kolkata
1  Krish   30  Bangalore
2   John   45    Florida

In [8]:
#Converting a DataFrame to a NumPy Array
import numpy as np
np.array(df)

array([['Aryan', 20, 'Kolkata'],
       ['Krish', 30, 'Bangalore'],
       ['John', 45, 'Florida']], dtype=object)

In [9]:
#Reading a CSV and Displaying the First Rows
df1=pd.read_csv('sales_data.csv')
df1.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [10]:
#Displaying the Last Rows
df1.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [11]:
#Selecting a DataFrame Column
df['Name']

0    Aryan
1    Krish
2     John
Name: Name, dtype: str

In [13]:
#Selecting a Row by Label
df.loc[0]

Name      Aryan
Age          20
City    Kolkata
Name: 0, dtype: object

In [14]:
#Selecting a Row by Position
df.iloc[1]

Name        Krish
Age            30
City    Bangalore
Name: 1, dtype: object

In [17]:
#Accessing Individual DataFrame Values
print(df.at[0,'Age'])
print(df.iat[0,2])

20
Kolkata

In [22]:
#Adding a Column to a DataFrame
df['Salary']=[50000,60000,80000]
df

    Name  Age       City  Salary
0  Aryan   20    Kolkata   50000
1  Krish   30  Bangalore   60000
2   John   45    Florida   80000

In [23]:
#Dropping a DataFrame Column
df.drop('Salary',axis=1,inplace=True)
df

C:\Users\Aryan\AppData\Local\Temp\ipykernel_23464\2701856805.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.drop('Salary',axis=1,inplace=True)

    Name  Age       City
0  Aryan   20    Kolkata
1  Krish   30  Bangalore
2   John   45    Florida

In [24]:
#Updating Values in a Column
df['Age']=df['Age']+1
df

    Name  Age       City
0  Aryan   21    Kolkata
1  Krish   31  Bangalore
2   John   46    Florida

In [ ]:
#Checking DataFrame Data Types
df=pd.read_csv('sales_data.csv')
print(df.dtypes)

Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object

In [26]:
#Generating Descriptive Statistics
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [28]:
#Calculating Average Revenue by Product Category
grouped = df.groupby('Product Category')['Total Revenue'].mean()

grouped

Product Category
Beauty Products     65.54750
Books               46.54825
Clothing           203.22325
Electronics        874.56025
Home Appliances    466.15400
Sports             358.16300
Name: Total Revenue, dtype: float64